print("enter first number")
a=int(input())
print("enter second number")
b=int(input())
print(f"Sum of the two numbers {a}and {b} is ", a+b)
print(f"subtraction of the two numbers {a}and {b} is ", a-b)
print(f"Exponantiation of the two numbers {a}and {b} is ", a**b)
print(f"Multiplication of the two numbers {a}and {b} is ", a*b)
print(f"Division of the two numbers {a}and {b} is ", a/b)
print(f"Modulus of the two numbers {a}and {b} is ", a%b)
print(f"Floor division of the two numbers {a}and {b} is ", a//b)